lib/live_table_example_web/router.ex
defmodule LiveTableExampleWeb.Router do
  use LiveTableExampleWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {LiveTableExampleWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", LiveTableExampleWeb do
    pipe_through :browser

    get "/", PageController, :index

    live_session :formats do
      live "/tables", TableLive.Index, :index
      live "/tables/new", TableLive.Index, :new
      live "/tables/:id/edit", TableLive.Index, :edit

      live "/tables/:id", TableLive.Show, :show
      live "/tables/:id/show/edit", TableLive.Show, :edit
    end
  end

  # Other scopes may use custom stacks.
  # scope "/api", LiveTableExampleWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser

      live_dashboard "/dashboard", metrics: LiveTableExampleWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/live_table_example_web/views/table_view.ex
defmodule LiveTableExampleWeb.TableView do
  use LiveTableExampleWeb, :view
end

lib/live_table_example_web/templates/table/form_component.html.heex
<div>
  <h2><%= @title %></h2>

  <.form
    let={f}
    for={@changeset}
    id="table-form"
    phx-target={@myself}
    phx-change="validate"
    phx-submit="save">
  
    <%= label f, :title %>
    <%= text_input f, :title %>
    <%= error_tag f, :title %>

    <table>
      <thead>
        <%= inputs_for f, :headers, fn fh -> %>
          <th>
            <%= text_input fh, :label %>
            <%= error_tag fh, :label %>

            <span>
              <%= content_tag :button,
                type: :button,
                phx_target: @myself,
                phx_click: :add_col,
                phx_value_index: fh.index
              do %>
                Add
              <% end %>
            </span>
            <span>
              <%= content_tag :button,
                type: :button,
                phx_target: @myself,
                phx_click: :delete_col,
                phx_value_index: fh.index
              do %>
                Delete
              <% end %>
            </span>
          </th>
        <% end %>

        <th><!-- Empty --></th>
      </thead>

      <tbody>
        <%= inputs_for f, :rows, fn fr -> %>
          <tr>

            <%= inputs_for fr, :items, fn fi -> %>
              <td>
                <%= textarea fi, :context %>
                <%= error_tag fi, :context %>
              </td>
            <% end %>

            <td style="text-align: center;">
              <%= content_tag :button,
                type: :button,
                phx_target: @myself,
                phx_click: :delete_row,
                phx_value_index: fr.index
              do %>
                Delete
              <% end %>
            </td>

          </tr>
        <% end %>

        <tr>
          <td colspan={length(inputs_for(f, :headers)) + 1} style="text-align: center;">
            <%= content_tag :button,
              type: :button,
              phx_target: @myself,
              phx_click: :add_row
            do %>
              Add
            <% end %>
          </td>
        </tr>
      </tbody>
    </table>
  
    <div>
      <%= submit "Save", phx_disable_with: "Saving..." %>
    </div>
  </.form>
</div>

lib/live_table_example_web/templates/table/index.html.heex
<h1>Listing Tables</h1>

<%= if @live_action in [:new, :edit] do %>
  <.modal return_to={Routes.table_index_path(@socket, :index)}>
    <.live_component
      module={LiveTableExampleWeb.TableLive.FormComponent}
      id={@table.id || :new}
      title={@page_title}
      action={@live_action}
      table={@table}
      return_to={Routes.table_index_path(@socket, :index)}
    />
  </.modal>
<% end %>

<table>
  <thead>
    <tr>
      <th>Title</th>

      <th></th>
    </tr>
  </thead>
  <tbody id="tables">
    <%= for table <- @tables do %>
      <tr id={"table-#{table.id}"}>
        <td><%= table.title %></td>

        <td>
          <span><%= live_redirect "Show", to: Routes.table_show_path(@socket, :show, table) %></span>
          <span><%= live_patch "Edit", to: Routes.table_index_path(@socket, :edit, table) %></span>
          <span><%= link "Delete", to: "#", phx_click: "delete", phx_value_id: table.id, data: [confirm: "Are you sure?"] %></span>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<span><%= live_patch "New Table", to: Routes.table_index_path(@socket, :new) %></span>

lib/live_table_example_web/templates/table/show.html.heex
<h1>Show Table</h1>

<%= if @live_action in [:edit] do %>
  <.modal return_to={Routes.table_show_path(@socket, :show, @table)}>
    <.live_component
      module={LiveTableExampleWeb.TableLive.FormComponent}
      id={@table.id}
      title={@page_title}
      action={@live_action}
      table={@table}
      return_to={Routes.table_show_path(@socket, :show, @table)}
    />
  </.modal>
<% end %>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @table.title %>
  </li>

</ul>

<span><%= live_patch "Edit", to: Routes.table_show_path(@socket, :edit, @table), class: "button" %></span> |
<span><%= live_redirect "Back", to: Routes.table_index_path(@socket, :index) %></span>